"""Activity catalogue for activities.html.

Hand-written details + scraped enrichment (Wikimedia Commons images, Google Maps rating/review themes)
merged by build_activities.py. Costs are approximate 2026 prices — confirm before going.
fields: id, day, title, cat, lat, lng, img_q (Commons search), maps_q (Google Maps query),
        summary, duration, cost, when, tips, link
"""

DAYS = [
    ("oct10", "Sat Oct 10", "Split", "Roman core + soft landing"),
    ("oct11", "Sun Oct 11", "Plitvice", "The non-negotiable nature day"),
    ("oct12", "Mon Oct 12", "Drive south", "Make the drive useful"),
    ("oct13", "Tue Oct 13", "Omiš & Cetina", "The adventure anchor"),
    ("oct14", "Wed Oct 14", "Hvar Town", "Fortress, waterfront, island reset"),
    ("oct15", "Thu Oct 15", "Hvar Island", "Villages, vineyards, old Greek fields"),
    ("oct16", "Fri Oct 16", "Dubrovnik", "Arrival + Mount Srđ"),
    ("oct17", "Sat Oct 17", "Dubrovnik", "Walls, sea and island"),
    ("oct18", "Sun Oct 18", "Herzegovina", "Mostar + waterfalls"),
    ("oct19", "Mon Oct 19", "Departure", "No stressful add-ons"),
]

A = [
    # ---------------- Oct 10 Split
    dict(id="palace", day="oct10", title="Diocletian's Palace & Peristyle", cat="culture", lat=43.5081, lng=16.4402,
         img_q="Peristyle Diocletian's Palace Split", maps_q="Peristyle, Split",
         summary="A 1,700-year-old Roman emperor's retirement palace that is still a living neighbourhood — 3,000 people live inside its walls. The Peristyle courtyard is the heart; the Vestibule's open dome has great acoustics (klapa singers often perform).",
         duration="1.5–3 h wandering", cost="Free to walk; combo tickets for cathedral/tower/crypt ~€15", when="Any time; magical after dark when lit",
         tips=["Go once in daylight and once at night.", "Guided walking tours (~1.5 h) explain the layers of history far better than signs."],
         link="https://visitsplit.com/en/447/diocletians-palace"),
    dict(id="belltower", day="oct10", title="Cathedral of St. Domnius & Bell Tower", cat="culture", lat=43.5078, lng=16.4405,
         img_q="Cathedral of Saint Domnius bell tower Split", maps_q="Cathedral of Saint Domnius Split",
         summary="Among the oldest cathedrals in the world still in use — built into Diocletian's own mausoleum. The 57 m Romanesque bell tower climb gives the best rooftop view of Split and the islands.",
         duration="45–60 min", cost="~€10–15 combo (cathedral, crypt, treasury, tower)", when="Morning, before cruise crowds",
         tips=["The top stairs are open metal grates — not for anyone nervous of heights.", "Modest dress (covered shoulders) for the cathedral."],
         link="https://www.visitsplit.com/en/443/cathedral-of-st-domnius"),
    dict(id="cellars", day="oct10", title="Palace Cellars (Substructures)", cat="culture", lat=43.5076, lng=16.4400,
         img_q="Substructures Diocletian's Palace cellars", maps_q="Diocletian's Cellars Split",
         summary="The vaulted basement halls that mirror the emperor's apartments above — among the best-preserved Roman substructures anywhere. Game of Thrones fans will recognise Daenerys' throne room.",
         duration="30–45 min", cost="~€10 (central hall with the souvenir market is free)", when="Midday / rain plan",
         tips=["The free central passage leads straight from the Riva into the Peristyle.", "Paid wings are quiet and atmospheric."],
         link="https://mgst.net/en/"),
    dict(id="goldengate", day="oct10", title="Golden Gate & Grgur Ninski", cat="culture", lat=43.5093, lng=16.4398,
         img_q="Gregory of Nin statue Split Golden Gate", maps_q="Grgur Ninski statue Split",
         summary="The palace's grand northern gate and Ivan Meštrović's giant bronze of the 10th-century bishop who fought for Croatian-language liturgy. Rubbing his toe is said to bring luck.",
         duration="15 min", cost="Free", when="Pair with the green market in the morning",
         tips=["Look for the tiny church squeezed into the gate's guard walkway."], link=""),
    dict(id="riva", day="oct10", title="Riva evening promenade", cat="relax", lat=43.5075, lng=16.4385,
         img_q="Riva promenade Split", maps_q="Riva Split",
         summary="Split's palm-lined waterfront, the city's living room. Coffee culture by day, evening passeggiata by night with the palace's southern façade behind you.",
         duration="As long as you like", cost="Free (coffee €2–4)", when="Sunset and after",
         tips=["Cafés on the Riva are pricier — step one lane back for better food."], link=""),
    dict(id="pazar", day="oct10", title="Green Market (Pazar)", cat="food", lat=43.5087, lng=16.4415,
         img_q="Green market Pazar Split", maps_q="Green Market Split",
         summary="Open-air produce market just east of the palace — figs, mandarins (in season mid-October!), local cheeses, dried figs, lavender and rakija.",
         duration="30 min", cost="Cheap snacks", when="Morning (winds down by 1 pm)",
         tips=["Mid-October is Neretva mandarin season — buy a bag."], link=""),
    dict(id="marjan", day="oct10", title="Marjan Hill: Vidilica → Telegrin", cat="nature", lat=43.5087, lng=16.4133,
         img_q="Marjan hill Split view", maps_q="Telegrin Marjan Split",
         summary="Pine-forest park on the peninsula right next to the Old Town. Stairs from Varoš reach the Vidilica café viewpoint in 15 min; keep climbing to Telegrin (178 m) for a 360° view of Split and the islands.",
         duration="45 min (Vidilica) to 2–3 h (full loop)", cost="Free", when="Late afternoon → sunset at Vidilica",
         tips=["Vidilica is a great sunset drink spot.", "The coastal road loop passes old hermitages carved into the cliffs."],
         link="https://www.marjan-parksuma.hr/en/"),
    dict(id="salona", day="oct10", title="Salona Archaeological Park", cat="alt", lat=43.5390, lng=16.4830,
         img_q="Salona archaeological site amphitheatre", maps_q="Salona Archaeological Park",
         summary="Ruins of the Roman provincial capital that preceded Split — amphitheatre, basilicas, city walls and early-Christian cemeteries, spread across olive groves.",
         duration="1.5–2 h", cost="~€8", when="Morning; little shade",
         tips=["15 min by car/taxi from Split; could pair with Klis Fortress on Oct 12 instead."], link=""),
    dict(id="bacvice", day="oct10", title="Bačvice Beach & picigin", cat="relax", lat=43.5020, lng=16.4470,
         img_q="Bačvice beach Split", maps_q="Bačvice Beach Split",
         summary="Split's sandy city beach, 10 min from the palace — home of picigin, the local sport of keeping a small ball in the air while splashing through the shallows.",
         duration="1–2 h", cost="Free", when="Warm afternoon (sea ~20 °C in October)",
         tips=["Kasjuni beach under Marjan is the quieter alternative."], link=""),

    # ---------------- Oct 11 Plitvice
    dict(id="plitvice", day="oct11", title="Plitvice Lakes – Program H / C", cat="nature", lat=44.8800, lng=15.6180,
         img_q="Plitvice Lakes National Park waterfalls autumn", maps_q="Plitvice Lakes National Park",
         summary="Croatia's UNESCO signature: 16 terraced lakes linked by waterfalls and wooden boardwalks. Program H (from Entrance 2) and C (from Entrance 1) both cover Upper and Lower Lakes with the Kozjak electric-boat crossing and the 78 m Veliki Slap.",
         duration="4–6 h (8–9 km)", cost="October ticket ~€23.50 pp (timed entry — book online)", when="Book the 8:00 slot; autumn colour peaks mid-October",
         tips=["Upper Lakes first, before tour groups arrive.", "Boardwalks get slippery in rain — shoes with grip.", "Program K (full circuit, ~18 km) only if the weather is perfect."],
         link="https://np-plitvicka-jezera.hr/en/plan-your-visit/istrazite-jezera/activities/lake-tour-programmes/"),
    dict(id="velikislap", day="oct11", title="Veliki Slap & Lower Lakes viewpoint", cat="nature", lat=44.9031, lng=15.6100,
         img_q="Veliki slap Plitvice", maps_q="Veliki Slap Plitvice",
         summary="The park's tallest waterfall (78 m) and the classic postcard view looking down over the Lower Lakes and boardwalks from the canyon rim near Entrance 1.",
         duration="Included in the walk (~45 min detour)", cost="Included", when="Morning light is best for the viewpoint",
         tips=["The rim viewpoint (Kozjačka) is 5 min from Entrance 1 — worth it even if you start from Entrance 2."], link=""),
    dict(id="rastoke", day="oct11", title="Rastoke water-mill village", cat="alt", lat=45.1224, lng=15.5808,
         img_q="Rastoke Slunj", maps_q="Rastoke Slunj",
         summary="A fairytale hamlet of old water mills and houses built over the cascades where the Slunjčica meets the Korana — a 'mini Plitvice' you can walk through in an hour.",
         duration="1 h", cost="~€5 for the mills area", when="Afternoon after the park",
         tips=["30 min north of Plitvice — only if energy remains."], link=""),
    dict(id="barac", day="oct11", title="Barać Caves", cat="alt", lat=45.0119, lng=15.5669,
         img_q="Barać caves", maps_q="Barać Caves",
         summary="Guided tours through a limestone cave system with stalactites and bat colonies — the best rain fallback near Plitvice.",
         duration="1 h tour", cost="~€12", when="Check October hours (reduced season)",
         tips=["Constant ~10 °C inside — bring a layer."], link="https://baracevespilje.hr/en/"),
    dict(id="lickakuca", day="oct11", title="Dinner: Lička Kuća", cat="food", lat=44.9020, lng=15.6080,
         img_q="Lika cuisine lamb peka", maps_q="Restaurant Lička kuća Plitvice",
         summary="Rustic restaurant beside Entrance 1 serving Lika mountain food — spit-roast lamb, Lika potatoes, trout, and hearty stews cooked on an open hearth.",
         duration="1–1.5 h", cost="€€", when="Dinner", tips=["Try Lički lonac (Lika pot stew) or lamb under the peka."], link=""),

    # ---------------- Oct 12 drive south
    dict(id="klis", day="oct12", title="Klis Fortress", cat="culture", lat=43.5596, lng=16.5234,
         img_q="Klis Fortress", maps_q="Klis Fortress",
         summary="A 2,000-year-old fortress on a razor ridge guarding the pass above Split — Ottoman frontier, Uskok stronghold, and Meereen in Game of Thrones. The walls look straight down to Split and the islands.",
         duration="1–1.5 h", cost="~€10", when="Late afternoon → sunset",
         tips=["Right on your Plitvice → Split route (20 min from Split).", "Grab spit-roast lamb in Klis village afterwards."], link="https://tvrdjava-klis.com/en/"),
    dict(id="trogir", day="oct12", title="Trogir Old Town & Kamerlengo", cat="culture", lat=43.5170, lng=16.2510,
         img_q="Trogir old town", maps_q="Trogir Old Town",
         summary="UNESCO-listed island town of Romanesque and Renaissance stone: the Cathedral of St Lawrence with Master Radovan's famous portal, a palm-lined waterfront, and the Kamerlengo Fortress tower at the tip.",
         duration="2–3 h incl. lunch", cost="Cathedral ~€8, Kamerlengo ~€5", when="Midday lunch stop",
         tips=["Easier with the car than Split — park across the bridge on the mainland."], link="https://visittrogir.hr/en/"),
    dict(id="krka", day="oct12", title="Krka NP – Skradinski Buk", cat="alt", lat=43.8050, lng=15.9630,
         img_q="Skradinski buk Krka", maps_q="Skradinski Buk",
         summary="Seventeen travertine cascades tumbling into a wide pool, with boardwalks and restored water mills. Different character from Plitvice — broader, more river-like.",
         duration="2–3 h", cost="October ticket ~€20 pp", when="Morning; only if you want a second waterfall park",
         tips=["Swimming is no longer permitted.", "Enter at Lozovac (drive) or take the boat from Skradin."], link="https://www.npkrka.hr/en/"),
    dict(id="sibenik", day="oct12", title="Šibenik – St. James Cathedral", cat="alt", lat=43.7367, lng=15.8889,
         img_q="Cathedral of St. James Šibenik", maps_q="Cathedral of St. James Šibenik",
         summary="A UNESCO Renaissance cathedral built entirely of stone without mortar, famous for its frieze of 71 carved human faces. Šibenik's hillside old town and fortresses are underrated.",
         duration="1.5–2 h", cost="Cathedral ~€5; St. Michael's Fortress ~€12", when="Pair with Krka",
         tips=["Adds the most detour friction of the Oct 12 options."], link=""),

    # ---------------- Oct 13 Omiš
    dict(id="rafting", day="oct13", title="Cetina River rafting", cat="adventure", lat=43.4400, lng=16.7700,
         img_q="Cetina river rafting Omiš", maps_q="Cetina rafting Omiš",
         summary="A 9–12 km float through the Cetina canyon: gentle rapids, cliff walls, calm swimming pools and a waterfall stop — fun more than extreme (grade I–III), finishing at Radmanove Mlinice.",
         duration="3–4 h incl. transfers", cost="~€40–50 pp (wetsuit, gear, guide); Split pickup ~+€10–15", when="Morning or early afternoon",
         tips=["Confirm operators still run mid-October (most do through October).", "Bring a change of clothes and a towel.", "Ask for Split hotel pickup and you won't need the car."],
         link="https://www.raftingcetinaomis.com/info"),
    dict(id="zipline", day="oct13", title="Zipline Omiš", cat="adventure", lat=43.4480, lng=16.7000,
         img_q="Zipline Omiš Cetina canyon", maps_q="Zipline Omiš",
         summary="Eight lines strung across the Cetina canyon, up to 700 m long and 150 m above the river. No skill needed, big views, pairs well with rafting on the same day.",
         duration="~3 h incl. transfer & short hike", cost="~€70 pp", when="Morning slot; closes in high wind",
         tips=["Wear closed-toe shoes.", "Combo rafting + zipline packages save a little."], link="https://www.zipline-croatia.com/"),
    dict(id="canyoning", day="oct13", title="Cetina canyoning", cat="adventure", lat=43.4380, lng=16.7400,
         img_q="Cetina canyon Omiš", maps_q="Canyoning Cetina Omiš",
         summary="The most adventurous option: swimming, scrambling, sliding and jumping down the canyon in a wetsuit, sometimes with a short rappel. Much more physical than rafting.",
         duration="4–5 h", cost="~€60–80 pp", when="Depends on water level — confirm it runs in October",
         tips=["Water is cold by October — wetsuits are thick but you'll still feel it."], link="https://www.visitomis.hr/en/active-holiday"),
    dict(id="forticaomis", day="oct13", title="Fortica (Starigrad) hike", cat="adventure", lat=43.4460, lng=16.6960,
         img_q="Starigrad fortress Omiš", maps_q="Starigrad Fortica Omiš",
         summary="A steep, rocky trail from Omiš old town up to the pirate-era fortress perched 300 m above the Cetina mouth. The payoff is the whole canyon, town and sea in one frame.",
         duration="2 h return (steep ~45–60 min up)", cost="~€5 at the top", when="Morning or late afternoon — no shade",
         tips=["Proper shoes; loose rock.", "Mirabela (10 min from town) is the easy alternative."], link=""),
    dict(id="mirabela", day="oct13", title="Mirabela Fortress & Omiš old town", cat="culture", lat=43.4450, lng=16.6900,
         img_q="Omiš old town Mirabela", maps_q="Mirabela Fortress Omiš",
         summary="Omiš was a pirate republic that taxed Venetian ships; Mirabela is its compact 13th-century tower right above the old town lanes, a quick climb for a canyon-mouth view.",
         duration="45 min", cost="~€4", when="Any time", tips=["Grab coffee on the square at the canyon mouth."], link=""),
    dict(id="radmanove", day="oct13", title="Lunch: Radmanove Mlinice", cat="food", lat=43.4450, lng=16.7270,
         img_q="Radmanove mlinice Cetina", maps_q="Radmanove Mlinice",
         summary="Old riverside water-mill complex turned restaurant in the canyon — shaded tables, peacocks, grilled trout and frogs' legs, usually the rafting finish point.",
         duration="1 h", cost="€€", when="Post-rafting lunch", tips=["Their home-made bread under the peka is the move."], link=""),
    dict(id="gubavica", day="oct13", title="Gubavica Waterfall viewpoint", cat="nature", lat=43.4338, lng=16.8898,
         img_q="Gubavica waterfall Zadvarje", maps_q="Gubavica waterfall",
         summary="A 50 m waterfall plunging into the Cetina canyon near Zadvarje — impressive from the viewpoint above, a short detour inland from Omiš.",
         duration="30–45 min", cost="Free", when="After rain it's at its best", tips=["Path is short but uneven."], link=""),
    dict(id="biokovo", day="oct13", title="Biokovo Skywalk", cat="alt", lat=43.3200, lng=17.0580,
         img_q="Biokovo Skywalk", maps_q="Skywalk Biokovo",
         summary="A glass horseshoe platform hanging off Biokovo mountain 1,228 m above Makarska — the Adriatic and islands spread out below. The strongest substitute if rafting is off.",
         duration="3–4 h round trip from Makarska", cost="Park entry ~€15–20 pp (incl. car road)", when="Clear, calm morning; road closes in bura wind",
         tips=["Single-lane mountain road, slow going.", "Check park hours — they shorten in October."], link="https://pp-biokovo.hr/en/plan-your-visit/working-hours"),

    # ---------------- Oct 14 Hvar Town
    dict(id="hvartown", day="oct14", title="Hvar Town & St. Stephen's Square", cat="culture", lat=43.1722, lng=16.4420,
         img_q="Hvar town square St Stephen", maps_q="St. Stephen's Square Hvar",
         summary="Dalmatia's largest square runs from the harbour to the Renaissance cathedral; around it, stepped lanes of stone palaces, the loggia and a harbour full of yachts. In October the party crowd is gone.",
         duration="2 h wandering", cost="Free", when="Afternoon arrival → evening", tips=["The quieter back lanes north of the square hide the best konobas."], link="https://visithvar.hr/"),
    dict(id="forticahvar", day="oct14", title="Fortica (Španjola) Fortress", cat="nature", lat=43.1745, lng=16.4410,
         img_q="Fortica Hvar fortress view Pakleni", maps_q="Fortica Hvar",
         summary="The 16th-century Spanish fortress above town — a 20-minute switchback climb through pine gardens to the classic view over the harbour and the Pakleni Islands.",
         duration="1 h", cost="~€10", when="Golden hour / sunset",
         tips=["If closed for the season, the path and walls outside still give the view."], link=""),
    dict(id="franciscan", day="oct14", title="Franciscan Monastery", cat="culture", lat=43.1695, lng=16.4455,
         img_q="Franciscan monastery Hvar", maps_q="Franciscan Monastery Hvar",
         summary="A 15th-century seaside monastery with a peaceful cloister, a 300-year-old cypress, and a large Last Supper painting — five minutes' walk along the water from the square.",
         duration="30–45 min", cost="~€5", when="Morning", tips=["Continue past it to the pebble coves on the east side."], link=""),
    dict(id="arsenal", day="oct14", title="Arsenal & Renaissance Theatre", cat="culture", lat=43.1717, lng=16.4412,
         img_q="Arsenal Hvar theatre", maps_q="Arsenal Hvar",
         summary="The Venetian galley arsenal on the square with one of Europe's oldest public theatres (1612) on its upper floor, open to all social classes from the start.",
         duration="30 min", cost="~€5", when="Rain option", tips=["The terrace has a good square-level harbour view."], link=""),
    dict(id="pakleni", day="oct14", title="Pakleni Islands (Palmižana)", cat="relax", lat=43.1630, lng=16.3960,
         img_q="Pakleni islands Palmižana", maps_q="Palmižana",
         summary="A chain of pine-covered islets just off Hvar Town with clear coves — Palmižana has a botanical garden and a couple of excellent restaurants. Pure 'luxury reset' material.",
         duration="Half day", cost="Taxi boat ~€10–15 pp return; private boat ~€150+", when="Calm-sea day only",
         tips=["Taxi boats thin out after mid-October — confirm the last return.", "Kayak rental is the active version."], link=""),
    dict(id="pokonji", day="oct14", title="Pokonji Dol beach walk", cat="relax", lat=43.1640, lng=16.4610,
         img_q="Pokonji Dol beach Hvar", maps_q="Pokonji Dol beach",
         summary="A 20-minute coastal walk east of town to a pebble beach with a small islet and lighthouse offshore. Clear water, few people out of season.",
         duration="1–2 h", cost="Free", when="Warm afternoon", tips=["Bring water shoes — pebbles and urchins."], link=""),
    dict(id="hulahula", day="oct14", title="Sunset: Hula Hula Beach Bar", cat="food", lat=43.1686, lng=16.4330,
         img_q="Hvar sunset Pakleni islands", maps_q="Hula Hula Beach Bar Hvar",
         summary="The famous west-promenade sunset bar facing the Pakleni Islands. In high summer it's a party; in October it's a relaxed cocktail with the best sunset in town.",
         duration="1–2 h", cost="€€", when="Sunset", tips=["May close for the season mid-October — the promenade rocks nearby work just as well."], link=""),

    # ---------------- Oct 15 Hvar island
    dict(id="grablje", day="oct15", title="Velo & Malo Grablje villages", cat="nature", lat=43.1700, lng=16.5080,
         img_q="Malo Grablje Hvar", maps_q="Velo Grablje",
         summary="Stone villages in the island's herb-scented interior: Velo Grablje was the lavender capital of Dalmatia; Malo Grablje was abandoned in the 1960s and now has one excellent konoba among the ruins.",
         duration="2–3 h with lunch", cost="Free", when="Late morning → lunch", tips=["Konoba Stori Komin in Malo Grablje is a standout lunch.", "Hike down the gorge from Malo Grablje to Milna."], link=""),
    dict(id="dubovica", day="oct15", title="Dubovica Beach", cat="relax", lat=43.1537, lng=16.5260,
         img_q="Dubovica beach Hvar", maps_q="Dubovica Beach Hvar",
         summary="A small, very photogenic cove with a stone summer house and turquoise water, reached by a 15-minute path down from the main road.",
         duration="1 h", cost="Free (parking lay-by on the road)", when="Morning light", tips=["Better as a view + swim stop than a full beach day."], link=""),
    dict(id="starigrad", day="oct15", title="Stari Grad & Tvrdalj", cat="culture", lat=43.1842, lng=16.5945,
         img_q="Tvrdalj Stari Grad Hvar", maps_q="Tvrdalj Stari Grad",
         summary="Founded by Greeks in 384 BC as Pharos, one of Europe's oldest towns. The harbour-front is lovely; Tvrdalj is the 16th-century poet Hektorović's fortified summer house with a fish pond.",
         duration="1.5–2 h", cost="Tvrdalj ~€5", when="Midday", tips=["Much calmer and more local than Hvar Town."], link=""),
    dict(id="plain", day="oct15", title="Stari Grad Plain (UNESCO)", cat="nature", lat=43.1780, lng=16.6300,
         img_q="Stari Grad Plain", maps_q="Stari Grad Plain",
         summary="An agricultural landscape laid out by Greek colonists 2,400 years ago — stone walls, stone shelters (trims) and vines still following the original grid.",
         duration="1 h drive/cycle through", cost="Free", when="Afternoon", tips=["Best experienced by bike on the flat farm roads."], link=""),
    dict(id="vrboska", day="oct15", title="Vrboska", cat="culture", lat=43.1810, lng=16.6750,
         img_q="Vrboska Hvar", maps_q="Vrboska Hvar",
         summary="Hvar's 'Little Venice' — a tiny fishing village wrapped around a narrow inlet with stone bridges and a fortress-church.",
         duration="45 min", cost="Free", when="Afternoon", tips=["Walk to Jelsa along the coast (~1 h) if you want a stroll."], link=""),
    dict(id="jelsa", day="oct15", title="Jelsa harbour", cat="food", lat=43.1618, lng=16.6932,
         img_q="Jelsa Hvar harbour", maps_q="Jelsa Hvar",
         summary="A pretty harbour town with café terraces under plane trees — a good lunch or coffee stop on the island loop.", duration="1 h", cost="€–€€", when="Lunch", tips=[], link=""),
    dict(id="nedjelja", day="oct15", title="Sveta Nedjelja & Zlatan Otok winery", cat="adventure", lat=43.1449, lng=16.6102,
         img_q="Sveta Nedjelja Hvar", maps_q="Zlatan Otok winery Sveta Nedjelja",
         summary="A steep south-coast hamlet reached through the one-lane Pitve tunnel: sea cliffs popular for sport climbing, a cave hermitage, and the Zlatan Otok winery producing Plavac Mali on vertiginous slopes.",
         duration="2–3 h", cost="Wine tasting ~€20–30 pp", when="Afternoon", tips=["Pitve tunnel is single-lane with traffic lights.", "Designate a driver or book a tasting tour."], link=""),

    # ---------------- Oct 16 Dubrovnik arrival
    dict(id="oldtown", day="oct16", title="Old Town orientation: Pile → Stradun → Old Port", cat="culture", lat=42.6410, lng=18.1098,
         img_q="Stradun Dubrovnik", maps_q="Stradun Dubrovnik",
         summary="Enter through Pile Gate, walk the polished limestone Stradun past Onofrio's Fountain to the Clock Tower and the Old Port. Then get lost in the stepped side-alleys.",
         duration="2 h", cost="Free", when="Late afternoon / evening after the ferry", tips=["Cruise-ship crowds thin out after ~5 pm."], link="https://tzdubrovnik.hr/"),
    dict(id="srd", day="oct16", title="Mount Srđ (cable car or hike)", cat="nature", lat=42.6480, lng=18.1150,
         img_q="Dubrovnik from Mount Srđ", maps_q="Dubrovnik Cable Car",
         summary="The classic overhead view of the walled city, Lokrum and the Elaphiti Islands. Ride the cable car in 4 minutes or hike the zig-zag trail in ~1 h; the Homeland War museum at Fort Imperial tells the 1991 siege story.",
         duration="1.5–2 h", cost="Cable car ~€30 return pp", when="Sunset", tips=["Hike up, cable car down is a good combo.", "Panorama restaurant at the top for sunset."], link="https://www.dubrovnikcablecar.com/timetable-and-prices/"),
    dict(id="buza", day="oct16", title="Buža Bar", cat="relax", lat=42.6388, lng=18.1102,
         img_q="Buža bar Dubrovnik cliffs", maps_q="Buža Bar Dubrovnik",
         summary="A 'hole in the wall' bar on the sea cliffs outside the southern walls — a drink with your feet over the Adriatic.", duration="1 h", cost="€€", when="Sunset",
         tips=["Cash was historically preferred — bring some."], link=""),

    # ---------------- Oct 17 Dubrovnik full day
    dict(id="walls", day="oct17", title="City Walls circuit", cat="culture", lat=42.6419, lng=18.1073,
         img_q="Dubrovnik city walls", maps_q="Walls of Dubrovnik",
         summary="The 2 km loop along intact medieval walls up to 25 m high — red roofs on one side, open sea on the other. Minčeta Tower is the highest point. The single most important Dubrovnik experience.",
         duration="1.5–2 h", cost="~€40 pp (includes Fort Lovrijenac)", when="8:00 opening — beat heat and cruise crowds",
         tips=["Walk counter-clockwise from Pile.", "Dubrovnik Pass may be better value if you'll do museums too."],
         link="https://tzdubrovnik.hr/lang/en/get/gradski_vodic/5302/city_walls_and_fortresses.html"),
    dict(id="lovrijenac", day="oct17", title="Fort Lovrijenac", cat="culture", lat=42.6410, lng=18.1040,
         img_q="Fort Lovrijenac", maps_q="Fort Lovrijenac",
         summary="The freestanding fortress on a 37 m sea rock outside Pile Gate — 'King's Landing' for Game of Thrones fans — with the best view back at the walls.", duration="30–45 min",
         cost="Included with walls ticket", when="Right after the walls", tips=["Inscription over the gate: 'Freedom is not sold for all the gold in the world.'"], link=""),
    dict(id="lokrum", day="oct17", title="Lokrum Island", cat="nature", lat=42.6270, lng=18.1210,
         img_q="Lokrum island", maps_q="Lokrum",
         summary="A car-free forest island 15 minutes by boat: Benedictine monastery ruins, a botanical garden, a tiny salt lake called the 'Dead Sea', rock swimming spots and free-roaming peacocks.",
         duration="3–4 h", cost="Boat incl. park entry ~€30 pp return", when="Afternoon; last boat back ~6 pm in October",
         tips=["No overnight stays allowed.", "Bring snacks — few food options off-season."], link="https://www.lokrum.hr/en/"),
    dict(id="kayak", day="oct17", title="Sea kayak to Lokrum & Betina Cave", cat="adventure", lat=42.6417, lng=18.1060,
         img_q="Sea kayaking Dubrovnik walls", maps_q="Sea kayaking Dubrovnik",
         summary="Guided kayak tour paddling under the city walls, around Lokrum and into Betina Cave beach for a snorkel. The active way to see the city from the sea.",
         duration="3 h", cost="~€40–50 pp", when="Calm morning or sunset tour", tips=["Only if sea is flat; operators cancel in wind."], link=""),
    dict(id="rector", day="oct17", title="Rector's Palace", cat="culture", lat=42.6403, lng=18.1109,
         img_q="Rector's Palace Dubrovnik", maps_q="Rector's Palace Dubrovnik",
         summary="Gothic-Renaissance seat of the Ragusan Republic's elected rector (who served just one month to prevent tyranny). Now the Cultural History Museum.", duration="1 h",
         cost="Included in Dubrovnik Pass", when="Rain plan", tips=["The atrium hosts concerts."], link=""),
    dict(id="maritime", day="oct17", title="Maritime Museum (St. John Fortress)", cat="culture", lat=42.6397, lng=18.1137,
         img_q="Saint John fortress Dubrovnik", maps_q="Maritime Museum Dubrovnik",
         summary="Dubrovnik's seafaring republic told through ship models and charts inside the fortress guarding the Old Port. Aquarium on the ground floor.", duration="45 min",
         cost="Included in Dubrovnik Pass", when="Rain plan", tips=[], link=""),
    dict(id="banje", day="oct17", title="Banje Beach", cat="relax", lat=42.6415, lng=18.1165,
         img_q="Banje beach Dubrovnik", maps_q="Banje Beach Dubrovnik",
         summary="The pebble beach just past Ploče Gate with the postcard view of the Old Town walls and harbour.", duration="1–2 h", cost="Free (loungers extra)",
         when="Warm afternoon", tips=[], link=""),
    dict(id="trsteno", day="oct17", title="Trsteno Arboretum", cat="alt", lat=42.7120, lng=17.9750,
         img_q="Trsteno Arboretum", maps_q="Trsteno Arboretum",
         summary="A 15th-century Renaissance garden estate above the sea with a giant plane tree, Neptune fountain and exotic plants — the Red Keep gardens in Game of Thrones.",
         duration="1.5 h", cost="~€15", when="Windy-sea alternative to Lokrum", tips=["25 min north by car or local bus 12/15/22."], link=""),

    # ---------------- Oct 18 Herzegovina
    dict(id="kravica", day="oct18", title="Kravica Waterfalls", cat="nature", lat=43.1566, lng=17.6078,
         img_q="Kravica waterfall", maps_q="Kravica Waterfall",
         summary="A 120 m-wide amphitheatre of 25 m cascades on the Trebižat river, forming a natural pool. In October the crowds are gone and the foliage turns.",
         duration="1–1.5 h", cost="~€10 (20 KM) pp", when="First stop of the day",
         tips=["Swimming only if brave — water is cold by October.", "Bring Bosnian marks (KM) or euros; cards patchy."], link="https://kravica.ba/en/for-visitors/"),
    dict(id="pocitelj", day="oct18", title="Počitelj", cat="culture", lat=43.1339, lng=17.7314,
         img_q="Počitelj", maps_q="Počitelj",
         summary="A stepped Ottoman-era hillside village with a mosque, hammam, madrasa and a hexagonal fortress tower overlooking the Neretva — 20 minutes of climbing for a spectacular view.",
         duration="1 h", cost="Free (small tower fee)", when="Mid-morning",
         tips=["Locals sell fresh pomegranate juice at the bottom — try it."], link="https://visit-bosniaherzegovina.com/Destinations/Pocitelj"),
    dict(id="mostar", day="oct18", title="Mostar – Stari Most & bazaar", cat="culture", lat=43.3373, lng=17.8150,
         img_q="Stari Most Mostar", maps_q="Stari Most",
         summary="The 16th-century Ottoman bridge, destroyed in 1993 and rebuilt stone by stone, arching 24 m over the emerald Neretva. Divers leap from it for tips. The Kujundžiluk bazaar lanes fill with copperwork and coffee.",
         duration="2–3 h", cost="Free", when="Midday (protect this time above all other Bosnia stops)",
         tips=["Try ćevapi and Bosnian coffee.", "Visit the war photo exhibition for context."], link=""),
    dict(id="koski", day="oct18", title="Koski Mehmed Pasha Mosque minaret", cat="culture", lat=43.3393, lng=17.8144,
         img_q="Koski Mehmed Pasha Mosque Mostar", maps_q="Koski Mehmed Pasha Mosque",
         summary="Climb the narrow minaret for the best view of Stari Most — or just stand in the mosque's riverside courtyard for the classic photo.", duration="30 min",
         cost="~€10 incl. minaret", when="While in Mostar", tips=["Tight spiral stairs."], link=""),
    dict(id="blagaj", day="oct18", title="Blagaj Tekke", cat="alt", lat=43.2567, lng=17.9024,
         img_q="Blagaj Tekke", maps_q="Blagaj Tekke",
         summary="A 16th-century dervish monastery tucked under a 200 m cliff at the source of the Buna river, one of Europe's biggest karst springs.",
         duration="1 h", cost="~€5", when="Only with a private driver and good timing",
         tips=["Riverside restaurants serve trout straight from the spring."], link=""),
    dict(id="kotor", day="oct18", title="Alternative: Kotor, Montenegro", cat="alt", lat=42.4247, lng=18.7712,
         img_q="Kotor bay old town", maps_q="Kotor Old Town",
         summary="Swap Bosnia for the Bay of Kotor: a walled Venetian town at the head of a fjord-like bay, with a 1,350-step climb to San Giovanni fortress.",
         duration="Full day (2–2.5 h each way + border)", cost="Fortress ~€15", when="If you'd prefer another adventure day", tips=["Perast is a beautiful stop en route."], link=""),

    # ---------------- Oct 19 departure
    dict(id="cavtat", day="oct19", title="Cavtat & Račić Mausoleum", cat="relax", lat=42.5808, lng=18.2180,
         img_q="Cavtat", maps_q="Cavtat",
         summary="A small seaside town 10 minutes from the airport: a palm-lined harbour, a pine-covered peninsula walk, the Meštrović-designed Račić Mausoleum and painter Vlaho Bukovac's house.",
         duration="2–3 h", cost="Mausoleum ~€5", when="Only if your flight is late", tips=["Store bags at the hotel or take them in the car."], link=""),
]

# ---------------- Food tours & cooking classes (2 per stop where found; researched via blogs/booking sites 2026-10-01)
A += [
    dict(id="splitcook", day="oct10", title="Cooking class: Split market → 3-course lunch", cat="food", lat=43.5085, lng=16.4415,
         img_q="Split green market Pazar", maps_q="Split Cooking Class",
         summary="Starts at the Pazar green market with a guide explaining what's in season, then a stop at Gligora for Pag island sheep cheese, then you cook a three-course Dalmatian lunch (think stuffed squid, risotto, pršut in red wine) and eat it with local wine.",
         duration="~5 h (morning → lunch)", cost="~€110–130 pp", when="Oct 10 morning — doubles as lunch",
         tips=["Book ahead; small groups fill up even in shoulder season.", "Tell them about dietary needs when booking — the menu follows the market."],
         link="https://www.byfood.com/experiences/split-cooking-class-27278"),
    dict(id="splitfoodtour", day="oct10", title="Food tour: Split Old Town tasting walk", cat="food", lat=43.5082, lng=16.4395,
         img_q="Split old town street food", maps_q="Split food tour Old Town",
         summary="Around five tasting stops at local konobas and bakeries inside and around the Palace, plus a traditional liqueur. Reviewers say it doubles as a history walking tour, so you can skip a separate guided walk.",
         duration="~3 h", cost="~€70–90 pp", when="Oct 10 lunchtime or early evening",
         tips=["A lunchtime slot replaces lunch.", "If you only do one of the two Split options, the tour is the lighter commitment on arrival day."],
         link="https://hellotickets.com/croatia/split/food-tour/a/pa-8161"),
    dict(id="plitvicecook", day="oct11", title="Cooking class: Lika home kitchen (Rastovača)", cat="food", lat=44.8985, lng=15.6125,
         img_q="Rastovača Plitvice", maps_q="Rastovača 14 Plitvice",
         summary="A family cooking class in a countryside house in Rastovača, a few minutes from Entrance 1: polenta with cream cheese, veal and lamb under the peka with potatoes and home-made bread, and uštipci (doughnuts) with jam — with home-made rakija.",
         duration="~4 h", cost="~$92 pp", when="Oct 11 late afternoon/evening, after the park",
         tips=["Only works if you start the park at 8:00 and are done by ~14:00.", "It replaces dinner — skip Lička kuća that night if you do this."],
         link="https://www.byfood.com/experiences/shared-rastovaca-cooking-class-40473"),
    dict(id="omissoparnik", day="oct13", title="Cooking class: soparnik in the Poljica villages", cat="food", lat=43.4560, lng=16.7380,
         img_q="Soparnik", maps_q="Soparnik Poljica",
         summary="Make soparnik, the Poljica region's thin chard-and-onion pie baked in embers (an EU-protected local speciality), with a family above Omiš, plus local wine and stories about village life.",
         duration="~2–3 h", cost="~€50–70 pp", when="Oct 13 afternoon, after rafting",
         tips=["Ask the rafting operator about timing — rafting finishes around midday.", "Radmanove Mlinice (already in the plan) also demos peka bread if you'd rather just eat."],
         link="https://theabroadguide.com/the-story-of-soparnik-cooking-class/"),
    dict(id="hvarfarmcook", day="oct15", title="Cooking class: farm-to-table on the Stari Grad Plain", cat="food", lat=43.1790, lng=16.6200,
         img_q="Stari Grad Plain fields", maps_q="Stari Grad Plain cooking class",
         summary="A mother-daughter team (Kornelija and Morana) hosts you in their garden on the UNESCO Stari Grad Plain: pick tomatoes and herbs, then cook dishes like Hvar octopus stew or black cuttlefish risotto, finishing with lemon olive-oil cake and wine at sunset.",
         duration="~4 h", cost="~€100–120 pp", when="Oct 15 afternoon — fits the Stari Grad day",
         tips=["Pairs well with the Plain e-bike ride the same day.", "Check that it's still running in mid-October before you plan around it."],
         link="https://travelingspoon.com/hosts/20139-cooking-class-on-hvar-island-a-farm-to-table-experience"),
    dict(id="hvargrablje", day="oct14", title="Cooking class: morning market → Velo Grablje", cat="food", lat=43.1660, lng=16.5160,
         img_q="Velo Grablje", maps_q="Velo Grablje",
         summary="Shop the Hvar Town market, transfer up to the lavender village of Velo Grablje, and cook a three-course lunch with drinks in a stone village house.",
         duration="~4–5 h", cost="~€100 pp", when="Oct 14 or 15 morning",
         tips=["Includes transfers, so no car needed.", "Easy to combine with the Malo Grablje / Stori Komin dinner in the same area — maybe pick one."],
         link="https://www.winerist.com/tours/hvar-island/morning-cooking-class-in-velo-grablje-from-hvar"),
    dict(id="dubkonavle", day="oct17", title="Cooking class: Konavle countryside farmhouse", cat="food", lat=42.5560, lng=18.3200,
         img_q="Konavle", maps_q="Konavle cooking class",
         summary="A small-group class (max ~8) at a family estate in the Konavle valley south of Dubrovnik: a four-course traditional meal using garden produce, often including zelena menestra (Konavle green stew), with local red and white wine. Hotel pickup included.",
         duration="~5 h incl. transfer", cost="~€120–150 pp", when="Oct 17 instead of Lokrum, or the morning of Oct 19 if your flight is late",
         tips=["Konavle is on the airport side of Dubrovnik — handy on departure day.", "Pickup means no car needed."],
         link="https://www.byfood.com/experiences/traditional-cooking-class-in-dubrovnik-countryside-29749"),
    dict(id="dubfoodtour", day="oct16", title="Food tour: Dubrovnik Old Town tasting walk", cat="food", lat=42.6410, lng=18.1100,
         img_q="Dubrovnik Stradun evening", maps_q="Do Eat Better Experience Dubrovnik",
         summary="A small-group walk (max 12) through the Old Town tasting local specialities — cured meats, cheese, seafood, local wine and sweets — with a local guide. Top-rated on TripAdvisor.",
         duration="~3 h", cost="~€80–100 pp", when="Oct 16 evening — an easy arrival-night dinner",
         tips=["A good way to find restaurants to come back to on Oct 17.", "Secret Food Tours runs a similar 3-hour Old Town tour."],
         link="https://doeatbetterexperience.com/"),
    dict(id="mostarcook", day="oct18", title="Cooking class: Bosnian burek & japrak in Mostar", cat="food", lat=43.3375, lng=17.8150,
         img_q="Burek Bosnia", maps_q="Mostar cooking class",
         summary="Learn to make burek and japrak (stuffed vine leaves) in a restaurant kitchen, with a rakija welcome and a three-course Bosnian meal with local wine or beer. Reviewers single out host Amina as patient and fun.",
         duration="~3 h", cost="~€58–67 pp", when="Oct 18 — only if you trim the waterfall stops",
         tips=["Mostar is a long day trip from Dubrovnik; a 3 h class means dropping Kravica or Počitelj.", "Better fit if you overnight in Mostar."],
         link="https://www.trip.com/things-to-do/detail/17482612"),
    dict(id="mostarfoodtour", day="oct18", title="Food tour: Mostar traditional food & drinks walk", cat="food", lat=43.3373, lng=17.8146,
         img_q="Ćevapi Bosnia", maps_q="Stari Most Mostar",
         summary="A ~3 h walk covering ćevapi and burek spots, a bazaar sweets-and-Bosnian-coffee stop and the local market. Run as a tip-based ('free') tour.",
         duration="~3 h (or just do the first hour)", cost="Tip-based + food", when="Oct 18 lunchtime",
         tips=["Doubles as lunch in Mostar.", "Ask the guide for the best burek and ćevapi even if you leave early."],
         link="https://guruwalk.com/walks/47083-mostar-free-traditional-food-and-drinks-tour"),
]

# Stops where no second food tour / class turned up in research
FOOD_GAPS = {
    "oct11": "Plitvice: only one bookable class found. Alternative: Lička kuća or a Lika cheese/honey farm (OPG) tasting, arranged locally.",
    "oct13": "Omiš: only the soparnik class found. Alternative: peka-bread demo and lunch at Radmanove Mlinice (already in the plan).",
}
