"""Paraphrased review themes, written from Google Maps reviews + topic tags scraped 2026-09-30.
(praise, watch-outs) — summaries, not quotes. Ratings/counts are merged from the scrape in build_activities.py.
"""
REVIEWS = {
    "palace": ("Reviewers love that it's a lived-in neighbourhood rather than a museum — ancient lanes, courtyards and cafés all blended together.", "Busy with cruise and tour groups midday; the central passage is lined with souvenir stalls."),
    "belltower": ("Praised for its setting inside the emperor's mausoleum and the view from the tower; people recommend the combined ticket (cathedral, crypt, baptistery, tower, treasury).", "The tower climb is steep and exposed near the top."),
    "cellars": ("People find the vaults the best way to grasp the palace's scale and layout; atmospheric and cool on a hot day.", "Go early (around 9:30) before tour boats arrive."),
    "goldengate": ("A fun, quick stop — everyone rubs the bishop's shiny big toe for a wish.", "Very quick; pair it with the market or the palace walk."),
    "riva": ("Loved for the waterfront walk, lively atmosphere and plenty of seating; it's where most boat tours depart.", "Restaurants right on the Riva are pricey and it gets crowded."),
    "pazar": ("Great fresh fruit and veg, friendly vendors who let you taste, and local olive oil and souvenirs.", "Some souvenir stalls sell mass-produced items."),
    "marjan": ("Highly rated viewpoint over Split and the islands.", "Stairs and some uphill walking to get there."),
    "salona": ("Impressive, large Roman site with an amphitheatre, basilicas and sarcophagi; free parking.", "Only partly excavated with limited signage — bring water, there's little shade."),
    "bacvice": ("One of the rare sandy beaches, shallow water and home of picigin; 10 minutes from the port.", "Crowded and the sand isn't great; much of it is concrete, so bring towels."),
    "plitvice": ("Consistently called a must-see: unreal water colours, waterfalls everywhere and a boat ride included; Route C gets strong recommendations.", "Crowds in peak hours; summer tickets were ~€40 (October is cheaper) — start early."),
    "velikislap": ("The photo highlight of the park — people take dozens of pictures here.", "Water flow varies by season; it's a detour from the main loop."),
    "rastoke": ("Described as fairytale-like — mills, cascades and cute wooden houses; an easy stop on the way to Plitvice.", "Small; parking is scattered around the village."),
    "barac": ("Guides get repeated shout-outs for being funny and informative; bats and big chambers; the park outside is pleasant too.", "Tours run at set times — check the October schedule."),
    "lickakuca": ("Better than people expect from a restaurant next to a big attraction — lamb under the bell, Lika potatoes and live music.", "Tourist-heavy location; service can be busy."),
    "klis": ("Big panoramic views over Split and the islands, well-preserved walls, sunset and Game of Thrones fans love it.", "Winding road and a tiny parking lot; entry fee applies."),
    "trogir": ("Loved for its atmospheric, Italian-feeling lanes and cathedral; feels less crowded than Split or Dubrovnik.", "Waterfront market is mostly tourist souvenirs."),
    "krka": ("Picture-postcard falls and boardwalks; the Skradin boat approach is recommended.", "Crowded at peak times and swimming is prohibited."),
    "sibenik": ("People are captivated by the stonework detail inside and out; the baptistery punches above its size.", "Entry fee is cash only."),
    "rafting": ("Families with kids and seasoned rafters both rave: beautiful scenery, calm and lively sections, a cave swim and cliff jumps. Operator (Rafting Cetina) praised for fast replies and transport.", "It's scenic fun rather than extreme whitewater."),
    "zipline": ("Near-perfect rating — often called the trip highlight; guides are funny, patient and reassuring; huge canyon views across 7–8 lines.", "Book ahead; it's weather-dependent."),
    "canyoning": ("Top-rated (Mirabella Tours) for professional, entertaining guides and smooth logistics; cliff jumps and river swims.", "Physically demanding; water is cold later in the season."),
    "forticaomis": ("A strenuous but rewarding climb with the best view in Omiš.", "No Google rating captured — steep, rocky path with no shade."),
    "mirabela": ("A quick, well-signed climb from town with sea and canyon views from the top.", "The final ladder to the rooftop is steep."),
    "radmanove": ("A gorgeous, peaceful riverside setting; home-made bread under the peka and trout are favourites.", "Food and service reviews are mixed on busy days."),
    "gubavica": ("A pleasant canyon-rim walk with several viewing terraces and easy free parking.", "Nice rather than spectacular — worth it if you're nearby."),
    "biokovo": ("Stunning views and a thrilling glass floor; wild horses along the road.", "The mountain road is long, narrow and single-lane with hairpins — allow time."),
    "hvartown": ("", ""),
    "forticahvar": ("The walk up through the gardens is called absolutely worth it, especially at sunset over the town and islands.", "Entry fee; the climb is steady uphill."),
    "franciscan": ("A peaceful seaside church and cloister a few minutes from the port; the ancient cypress and art are highlights, and concerts are sometimes held here.", "Small — 30 minutes is plenty."),
    "arsenal": ("Beautiful architecture and interesting galley-fleet history, plus the historic theatre.", "Some find the inside plain — more exhibit than museum."),
    "pakleni": ("Crystal-clear turquoise coves perfect for swimming and snorkelling; often the highlight of island-hopping trips.", "Only reachable by boat — check off-season taxi-boat times."),
    "pokonji": ("A pretty pebble cove with clear water.", "Sea urchins and pebbles — bring water shoes."),
    "hulahula": ("Great sunset atmosphere, friendly service and people-watching.", "Drinks are expensive and it's cash-focused; may be winding down for the season."),
    "grablje": ("Konoba Stori Komin in Malo Grablje is adored — an authentic, magical meal in an abandoned village away from Hvar Town's noise; pre-order the lamb or octopus under the bell.", "Cash only; call ahead to book and pre-order peka dishes."),
    "dubovica": ("A beautiful white-pebble cove with crystal water and few people outside peak season.", "Steep ~700 m path down (and back up) — wear real shoes, not flip-flops."),
    "starigrad": ("A tranquil Renaissance garden with a fish pond; small but lovely and cheap to enter.", "Cash only (~€5)."),
    "plain": ("A rare intact ancient Greek landscape; e-biking through it gets great reviews.", "It's farmland — the appeal is the history and atmosphere, not a single sight."),
    "nedjelja": ("Excellent, aromatic local wines and food; the underwater wine cellar is a unique touch.", "The drive through the Pitve tunnel is 'adventurous'."),
    "oldtown": ("One of the most stunning medieval main streets anywhere; the side alleys are spectacular.", "Hectic by day — go early morning or evening."),
    "srd": ("Magnificent views of the Old Town, especially at sunset; many suggest cable car up and walk down.", "Pricey (~€30 return per person); queues at peak times."),
    "buza": ("Unbeatable cliffside sunset views over the Adriatic.", "Cash only, pricey drinks and no toilets."),
    "walls": ("Surprisingly worth the price — continuous views over terracotta roofs and sea, with pit stops along the way.", "Expensive, lots of stairs, and hot in the middle of the day; allow 90+ minutes."),
    "lovrijenac": ("Great views of the Old Town and walls; included with the walls ticket or Dubrovnik Pass.", "~€15 on its own if you don't have the walls ticket."),
    "lokrum": ("Exceptionally beautiful nature reserve with peacocks, rabbits, the monastery, botanical garden and an Iron Throne replica.", "Boat is ~€30 return per person; weather-dependent."),
    "kayak": ("", ""),
    "rector": ("The courtyard and staircase are beautiful (Game of Thrones fans will recognise them); dungeon and armoury add interest.", "Some find the museum content thin for the price."),
    "maritime": ("Small but well-organised, with genuinely informative displays on the republic's seafaring history.", "Small — under an hour."),
    "banje": ("Gorgeous Old Town views and a relaxed beach-club vibe.", "Beach-club loungers are expensive (~€70 for two sunbeds and an umbrella)."),
    "trsteno": ("A beautiful historic garden with sea views, aqueduct and giant plane trees; Game of Thrones fans love it.", "Cash only; allow 1.5–2 hours to explore properly."),
    "kravica": ("Stunning waterfalls with clear water — arrive first thing to beat the crowds.", "Busy midday; very cold water."),
    "pocitelj": ("A hidden gem — a stone village climbing the hillside with great photo spots and river views; easy from Mostar.", "Quite a climb up uneven steps."),
    "mostar": ("Universally called a must-see — the bridge's stone arch over the emerald Neretva, the bazaar and the history.", "Crowded and the stone is slippery — wear shoes with grip."),
    "koski": ("The minaret view of Stari Most is famous, and the interior is beautiful.", "Closed during prayer times; ~€10 entry."),
    "blagaj": ("A breathtaking, peaceful setting under the cliff at the river spring; quieter in the evening.", "Busy with tour groups midday."),
    "kotor": ("One of the best-preserved medieval towns people have visited — ramparts, alleys and cats.", "Crowded when cruise ships are in; the fortress climb is steep."),
    "cavtat": ("The Račić Mausoleum is impressive and moving, with lovely views from the hilltop.", "Many stairs up the hill to reach it."),
}

# Google Maps results that matched a specific operator rather than the generic activity
OPERATOR = {"rafting": "Rafting Cetina", "zipline": "Zipline Croatia", "canyoning": "Mirabella Tours", "grablje": "Konoba Stori Komin",
            "nedjelja": "Zlatan Otok winery", "cavtat": "Račić Mausoleum", "srd": "Dubrovnik Cable Car", "rastoke": "Rastoke Old Mill"}
SKIP_RATING = {"kayak", "hvartown", "forticaomis"}  # scrape returned an unrelated or empty place
